/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_api_v1_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Instruments */
        get: operations["list_instruments_api_v1_instruments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Instrument */
        get: operations["get_instrument_api_v1_instruments__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{symbol}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Instrument Prices */
        get: operations["list_instrument_prices_api_v1_instruments__symbol__prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{symbol}/corporate-actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Instrument Corporate Actions */
        get: operations["list_instrument_corporate_actions_api_v1_instruments__symbol__corporate_actions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{symbol}/indicators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Instrument Indicators */
        get: operations["list_instrument_indicators_api_v1_instruments__symbol__indicators_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scanner/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scan Candidates */
        get: operations["list_scan_candidates_api_v1_scanner_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{symbol}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Instrument Candidates */
        get: operations["list_instrument_candidates_api_v1_instruments__symbol__candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Backtest Runs */
        get: operations["list_backtest_runs_api_v1_backtests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtests/{backtest_run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Backtest Run */
        get: operations["get_backtest_run_api_v1_backtests__backtest_run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtests/{backtest_run_id}/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Backtest Trades */
        get: operations["list_backtest_trades_api_v1_backtests__backtest_run_id__trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtests/{backtest_run_id}/equity-curve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Backtest Equity Curve */
        get: operations["list_backtest_equity_curve_api_v1_backtests__backtest_run_id__equity_curve_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/trade-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trade Plans */
        get: operations["list_trade_plans_api_v1_risk_trade_plans_get"];
        put?: never;
        /** Create Trade Plan */
        post: operations["create_trade_plan_api_v1_risk_trade_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/trade-plans/{trade_plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trade Plan */
        get: operations["get_trade_plan_api_v1_risk_trade_plans__trade_plan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Executions */
        get: operations["list_executions_api_v1_executions_get"];
        put?: never;
        /** Record Execution */
        post: operations["record_execution_api_v1_executions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Positions */
        get: operations["list_positions_api_v1_positions_get"];
        put?: never;
        /** Create Planned Position */
        post: operations["create_planned_position_api_v1_positions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions/{position_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Position */
        post: operations["cancel_position_api_v1_positions__position_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions/{position_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Position */
        get: operations["get_position_api_v1_positions__position_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions/{position_id}/journal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Journal */
        get: operations["get_journal_api_v1_positions__position_id__journal_get"];
        put?: never;
        /** Upsert Journal */
        post: operations["upsert_journal_api_v1_positions__position_id__journal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/performance/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Performance Summary */
        get: operations["get_performance_summary_api_v1_performance_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/performance/by-setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Performance By Setup */
        get: operations["get_performance_by_setup_api_v1_performance_by_setup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/performance/by-sector": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Performance By Sector */
        get: operations["get_performance_by_sector_api_v1_performance_by_sector_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/performance/by-holding-period": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Performance By Holding Period */
        get: operations["get_performance_by_holding_period_api_v1_performance_by_holding_period_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/performance/by-score-bucket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Performance By Score Bucket */
        get: operations["get_performance_by_score_bucket_api_v1_performance_by_score_bucket_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/performance/behavior": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Performance Behavior */
        get: operations["get_performance_behavior_api_v1_performance_behavior_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_api_v1_ai_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Snapshots */
        get: operations["list_snapshots_api_v1_ai_snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/snapshots/{snapshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Snapshot */
        get: operations["get_snapshot_api_v1_ai_snapshots__snapshot_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intelligence/breadth/compute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute Breadth */
        post: operations["compute_breadth_api_v1_intelligence_breadth_compute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intelligence/breadth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Breadth */
        get: operations["get_breadth_api_v1_intelligence_breadth_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intelligence/breadth/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Breadth History */
        get: operations["list_breadth_history_api_v1_intelligence_breadth_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intelligence/sector-performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sector Performance */
        get: operations["get_sector_performance_api_v1_intelligence_sector_performance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intelligence/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_v1_intelligence_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alerts */
        get: operations["list_alerts_api_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Alerts */
        get: operations["stream_alerts_api_v1_alerts_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ops Status */
        get: operations["ops_status_api_v1_ops_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/job-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Job Runs */
        get: operations["list_job_runs_api_v1_ops_job_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Calendar Days */
        get: operations["list_calendar_days_api_v1_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertOut */
        AlertOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            alert_type: components["schemas"]["AlertType"];
            /**
             * Instrument Id
             * Format: uuid
             */
            instrument_id: string;
            /**
             * Trigger Date
             * Format: date
             */
            trigger_date: string;
            /** Message */
            message: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * AlertType
         * @enum {string}
         */
        AlertType: "SETUP_DETECTED" | "BREAKOUT" | "PRICE_NEAR_ENTRY" | "PRICE_NEAR_STOP" | "PRICE_NEAR_TARGET" | "UNUSUAL_VOLUME" | "STALE_DATA" | "IMPORTANT_EVENT";
        /** AnalysisSnapshotOut */
        AnalysisSnapshotOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Instrument Id */
            instrument_id: string | null;
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Prompt Version */
            prompt_version: string;
            /** Question */
            question: string;
            /** Tool Calls */
            tool_calls: {
                [key: string]: unknown;
            }[];
            /** Structured Data Snapshot */
            structured_data_snapshot: {
                [key: string]: unknown;
            }[];
            /** Response */
            response: string;
            /** Guardrail Flags */
            guardrail_flags: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /** Question */
            question: string;
            /** Symbol */
            symbol?: string | null;
        };
        /** BacktestMetricsOut */
        BacktestMetricsOut: {
            /** Total Return Pct */
            total_return_pct: number;
            /** Cagr Pct */
            cagr_pct: number | null;
            /** Win Rate Pct */
            win_rate_pct: number;
            /** Avg Win */
            avg_win: number | null;
            /** Avg Loss */
            avg_loss: number | null;
            /** Expectancy */
            expectancy: number | null;
            /** Profit Factor */
            profit_factor: number | null;
            /** Max Drawdown Pct */
            max_drawdown_pct: number;
            /** Sharpe Ratio */
            sharpe_ratio: number | null;
            /** Trade Count */
            trade_count: number;
            /** Avg Holding Days */
            avg_holding_days: number | null;
            /** R Distribution */
            r_distribution: number[];
        };
        /** BacktestRunDetailOut */
        BacktestRunDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Strategy Version */
            strategy_version: string;
            setup_type: components["schemas"]["SetupType"];
            /** Min Score */
            min_score: number;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Initial Capital */
            initial_capital: number;
            /** Risk Per Trade Pct */
            risk_per_trade_pct: number;
            /** Max Concurrent Positions */
            max_concurrent_positions: number;
            /** Fee Bps */
            fee_bps: number;
            /** Slippage Bps */
            slippage_bps: number;
            /** Stop Atr Multiplier */
            stop_atr_multiplier: number;
            /** Target Atr Multiplier */
            target_atr_multiplier: number;
            /** Max Holding Days */
            max_holding_days: number;
            execution_model: components["schemas"]["ExecutionModel"];
            /** Indicator Version */
            indicator_version: string;
            /** Score Version */
            score_version: string;
            status: components["schemas"]["BacktestStatus"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Error Message */
            error_message: string | null;
            metrics: components["schemas"]["BacktestMetricsOut"] | null;
        };
        /** BacktestRunOut */
        BacktestRunOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Strategy Version */
            strategy_version: string;
            setup_type: components["schemas"]["SetupType"];
            /** Min Score */
            min_score: number;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Initial Capital */
            initial_capital: number;
            /** Risk Per Trade Pct */
            risk_per_trade_pct: number;
            /** Max Concurrent Positions */
            max_concurrent_positions: number;
            /** Fee Bps */
            fee_bps: number;
            /** Slippage Bps */
            slippage_bps: number;
            /** Stop Atr Multiplier */
            stop_atr_multiplier: number;
            /** Target Atr Multiplier */
            target_atr_multiplier: number;
            /** Max Holding Days */
            max_holding_days: number;
            execution_model: components["schemas"]["ExecutionModel"];
            /** Indicator Version */
            indicator_version: string;
            /** Score Version */
            score_version: string;
            status: components["schemas"]["BacktestStatus"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Error Message */
            error_message: string | null;
        };
        /**
         * BacktestStatus
         * @enum {string}
         */
        BacktestStatus: "RUNNING" | "SUCCEEDED" | "FAILED";
        /** BacktestTradeOut */
        BacktestTradeOut: {
            /** Symbol */
            symbol: string;
            setup_type: components["schemas"]["SetupType"];
            /**
             * Signal Date
             * Format: date
             */
            signal_date: string;
            /**
             * Entry Date
             * Format: date
             */
            entry_date: string;
            /** Entry Price */
            entry_price: number;
            /** Stop Price */
            stop_price: number;
            /** Target Price */
            target_price: number;
            /** Exit Date */
            exit_date: string | null;
            /** Exit Price */
            exit_price: number | null;
            exit_reason: components["schemas"]["ExitReason"] | null;
            /** Quantity */
            quantity: number;
            /** Fees Paid */
            fees_paid: number;
            /** Slippage Cost */
            slippage_cost: number;
            /** Pnl */
            pnl: number | null;
            /** R Multiple */
            r_multiple: number | null;
            /** Holding Days */
            holding_days: number | null;
        };
        /** BehaviorEntryOut */
        BehaviorEntryOut: {
            /** Position Id */
            position_id: string;
            /** Stop Violated */
            stop_violated: boolean | null;
            /** Entry Deviation Pct */
            entry_deviation_pct: number | null;
            /** Quantity Deviation Pct */
            quantity_deviation_pct: number | null;
        };
        /** BreadthComputeRequest */
        BreadthComputeRequest: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
        };
        /** BreadthSnapshotOut */
        BreadthSnapshotOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Breadth Version */
            breadth_version: string;
            /** Universe Size */
            universe_size: number;
            /** Pct Above Sma50 */
            pct_above_sma50: number | null;
            /** Pct Above Sma200 */
            pct_above_sma200: number | null;
            /** Advancers */
            advancers: number;
            /** Decliners */
            decliners: number;
            /** Unchanged */
            unchanged: number;
            /** New Highs 20 */
            new_highs_20: number;
            /** New Lows 20 */
            new_lows_20: number;
            regime: components["schemas"]["MarketRegime"];
            /** Regime Version */
            regime_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CalendarDayOut */
        CalendarDayOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Is Trading Day */
            is_trading_day: boolean;
            /** Source */
            source: string;
        };
        /** CorporateActionOut */
        CorporateActionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            action_type: components["schemas"]["CorporateActionType"];
            /**
             * Ex Date
             * Format: date
             */
            ex_date: string;
            /** Effective Date */
            effective_date: string | null;
            /** Announced At */
            announced_at: string | null;
            /** Ratio */
            ratio: number | null;
            /** Amount */
            amount: number | null;
            /** Source */
            source: string;
        };
        /**
         * CorporateActionType
         * @enum {string}
         */
        CorporateActionType: "SPLIT" | "REVERSE_SPLIT" | "CASH_DIVIDEND" | "STOCK_DIVIDEND" | "BONUS_ISSUE" | "RIGHTS_ISSUE" | "OTHER";
        /**
         * DataQualityStatus
         * @enum {string}
         */
        DataQualityStatus: "VALID" | "INVALID" | "STALE" | "SUSPECT";
        /** EquityPointOut */
        EquityPointOut: {
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Equity Value */
            equity_value: number;
        };
        /** EventOut */
        EventOut: {
            /**
             * Instrument Id
             * Format: uuid
             */
            instrument_id: string;
            /** Symbol */
            symbol: string;
            /** Event Type */
            event_type: string;
            /**
             * Announced At
             * Format: date-time
             */
            announced_at: string;
            /** Availability Is Estimated */
            availability_is_estimated: boolean;
            /**
             * Ex Date
             * Format: date
             */
            ex_date: string;
            /** Effective Date */
            effective_date: string | null;
            /** Description */
            description: string;
        };
        /** ExecutionCreate */
        ExecutionCreate: {
            /** Symbol */
            symbol: string;
            side: components["schemas"]["ExecutionSide"];
            /** Quantity */
            quantity: number;
            /** Price */
            price: number;
            /** Fee */
            fee: number;
            /**
             * Executed At
             * Format: date-time
             */
            executed_at: string;
            /** Trade Plan Id */
            trade_plan_id?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * ExecutionModel
         * @enum {string}
         */
        ExecutionModel: "NEXT_OPEN";
        /** ExecutionOut */
        ExecutionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Position Id
             * Format: uuid
             */
            position_id: string;
            /**
             * Instrument Id
             * Format: uuid
             */
            instrument_id: string;
            /** Trade Plan Id */
            trade_plan_id: string | null;
            side: components["schemas"]["ExecutionSide"];
            /** Quantity */
            quantity: number;
            /** Price */
            price: number;
            /** Fee */
            fee: number;
            /** Realized Pnl Impact */
            realized_pnl_impact: number | null;
            /**
             * Executed At
             * Format: date-time
             */
            executed_at: string;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ExecutionSide
         * @enum {string}
         */
        ExecutionSide: "BUY" | "SELL";
        /**
         * ExitReason
         * @enum {string}
         */
        ExitReason: "STOP" | "TARGET" | "TIME" | "END_OF_BACKTEST";
        /** GroupPerformanceOut */
        GroupPerformanceOut: {
            /** Key */
            key: string | null;
            /** Closed Position Count */
            closed_position_count: number;
            /** Total Realized Pnl */
            total_realized_pnl: number;
            /** Win Rate Pct */
            win_rate_pct: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IndicatorSnapshotOut */
        IndicatorSnapshotOut: {
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Indicator Version */
            indicator_version: string;
            /** Sma 20 */
            sma_20: number | null;
            /** Sma 50 */
            sma_50: number | null;
            /** Sma 200 */
            sma_200: number | null;
            /** Ema 20 */
            ema_20: number | null;
            /** Ema 50 */
            ema_50: number | null;
            /** Rsi 14 */
            rsi_14: number | null;
            /** Atr 14 */
            atr_14: number | null;
            /** Macd */
            macd: number | null;
            /** Macd Signal */
            macd_signal: number | null;
            /** Macd Histogram */
            macd_histogram: number | null;
            /** Bb Upper */
            bb_upper: number | null;
            /** Bb Middle */
            bb_middle: number | null;
            /** Bb Lower */
            bb_lower: number | null;
            /** Volume Sma 20 */
            volume_sma_20: number | null;
            /** Relative Volume */
            relative_volume: number | null;
            /** Rolling High 20 */
            rolling_high_20: number | null;
            /** Rolling Low 20 */
            rolling_low_20: number | null;
            /** Return 1D */
            return_1d: number | null;
            /** Volatility 20 */
            volatility_20: number | null;
        };
        /** InstrumentOut */
        InstrumentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Symbol */
            symbol: string;
            /** Company Name */
            company_name: string;
            /** Exchange */
            exchange: string;
            /** Currency */
            currency: string;
            /** Security Type */
            security_type: string;
            /** Sector */
            sector: string | null;
            /** Subsector */
            subsector: string | null;
            /** Listing Date */
            listing_date: string | null;
            /** Delisting Date */
            delisting_date: string | null;
            status: components["schemas"]["ListingStatus"];
            /** Source */
            source: string;
            /** Source Symbol */
            source_symbol: string;
        };
        /** JobRunOut */
        JobRunOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            job_type: components["schemas"]["JobType"];
            /**
             * Run Date
             * Format: date
             */
            run_date: string;
            status: components["schemas"]["JobStatus"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "RUNNING" | "SUCCEEDED" | "FAILED" | "PARTIAL";
        /**
         * JobType
         * @enum {string}
         */
        JobType: "INGESTION" | "INDICATORS" | "SCANNER" | "RISK_PLANS" | "BREADTH" | "ALERTS";
        /** JournalOut */
        JournalOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Position Id
             * Format: uuid
             */
            position_id: string;
            /** Thesis */
            thesis: string | null;
            /** Market Context */
            market_context: string | null;
            /** Execution Quality */
            execution_quality: string | null;
            /** Behavioral Notes */
            behavioral_notes: string | null;
            /** Plan Adherence Notes */
            plan_adherence_notes: string | null;
            /** Mistakes */
            mistakes: string | null;
            /** Lessons */
            lessons: string | null;
            /** Reference Urls */
            reference_urls: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** JournalUpsert */
        JournalUpsert: {
            /** Thesis */
            thesis?: string | null;
            /** Market Context */
            market_context?: string | null;
            /** Execution Quality */
            execution_quality?: string | null;
            /** Behavioral Notes */
            behavioral_notes?: string | null;
            /** Plan Adherence Notes */
            plan_adherence_notes?: string | null;
            /** Mistakes */
            mistakes?: string | null;
            /** Lessons */
            lessons?: string | null;
            /** Reference Urls */
            reference_urls?: string[];
        };
        /**
         * ListingStatus
         * @enum {string}
         */
        ListingStatus: "ACTIVE" | "SUSPENDED" | "DELISTED";
        /**
         * MarketRegime
         * @enum {string}
         */
        MarketRegime: "RISK_ON" | "RISK_OFF" | "NEUTRAL";
        /** OpsStatusOut */
        OpsStatusOut: {
            /** Queue Depth */
            queue_depth: number;
            /** Worker Count */
            worker_count: number;
            /** Stages */
            stages: components["schemas"]["StageStatusOut"][];
            /** Recent Failure Count */
            recent_failure_count: number;
        };
        /** Page[AlertOut] */
        Page_AlertOut_: {
            /** Items */
            items: components["schemas"]["AlertOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** Page[AnalysisSnapshotOut] */
        Page_AnalysisSnapshotOut_: {
            /** Items */
            items: components["schemas"]["AnalysisSnapshotOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** Page[BacktestRunOut] */
        Page_BacktestRunOut_: {
            /** Items */
            items: components["schemas"]["BacktestRunOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** Page[BacktestTradeOut] */
        Page_BacktestTradeOut_: {
            /** Items */
            items: components["schemas"]["BacktestTradeOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** Page[BreadthSnapshotOut] */
        Page_BreadthSnapshotOut_: {
            /** Items */
            items: components["schemas"]["BreadthSnapshotOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** Page[CalendarDayOut] */
        Page_CalendarDayOut_: {
            /** Items */
            items: components["schemas"]["CalendarDayOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** Page[CorporateActionOut] */
        Page_CorporateActionOut_: {
            /** Items */
            items: components["schemas"]["CorporateActionOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** Page[EquityPointOut] */
        Page_EquityPointOut_: {
            /** Items */
            items: components["schemas"]["EquityPointOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** Page[EventOut] */
        Page_EventOut_: {
            /** Items */
            items: components["schemas"]["EventOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** Page[ExecutionOut] */
        Page_ExecutionOut_: {
            /** Items */
            items: components["schemas"]["ExecutionOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** Page[IndicatorSnapshotOut] */
        Page_IndicatorSnapshotOut_: {
            /** Items */
            items: components["schemas"]["IndicatorSnapshotOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** Page[InstrumentOut] */
        Page_InstrumentOut_: {
            /** Items */
            items: components["schemas"]["InstrumentOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** Page[JobRunOut] */
        Page_JobRunOut_: {
            /** Items */
            items: components["schemas"]["JobRunOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** Page[PositionOut] */
        Page_PositionOut_: {
            /** Items */
            items: components["schemas"]["PositionOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** Page[PriceBarOut] */
        Page_PriceBarOut_: {
            /** Items */
            items: components["schemas"]["PriceBarOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** Page[ScanCandidateOut] */
        Page_ScanCandidateOut_: {
            /** Items */
            items: components["schemas"]["ScanCandidateOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** Page[TradePlanOut] */
        Page_TradePlanOut_: {
            /** Items */
            items: components["schemas"]["TradePlanOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** PerformanceSummaryOut */
        PerformanceSummaryOut: {
            /** Initial Capital */
            initial_capital: number;
            /** Total Realized Pnl */
            total_realized_pnl: number;
            /** Unrealized Pnl */
            unrealized_pnl: number;
            /** Exposure */
            exposure: number;
            /** Closed Position Count */
            closed_position_count: number;
            /** Win Rate Pct */
            win_rate_pct: number;
            /** Avg Win */
            avg_win: number | null;
            /** Avg Loss */
            avg_loss: number | null;
            /** Expectancy */
            expectancy: number | null;
            /** Profit Factor */
            profit_factor: number | null;
            /** Max Drawdown Pct */
            max_drawdown_pct: number;
            /** Sharpe Ratio */
            sharpe_ratio: number | null;
            /** Equity Curve */
            equity_curve: [
                string,
                number
            ][];
        };
        /** PlannedPositionCreate */
        PlannedPositionCreate: {
            /**
             * Trade Plan Id
             * Format: uuid
             */
            trade_plan_id: string;
        };
        /** PortfolioPositionIn */
        PortfolioPositionIn: {
            /** Symbol */
            symbol: string;
            /** Sector */
            sector?: string | null;
            /** Allocation Amount */
            allocation_amount: number;
        };
        /** PositionOut */
        PositionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Instrument Id
             * Format: uuid
             */
            instrument_id: string;
            /** Trade Plan Id */
            trade_plan_id: string | null;
            status: components["schemas"]["PositionStatus"];
            /** Quantity Open */
            quantity_open: number;
            /** Avg Entry Price */
            avg_entry_price: number | null;
            /** Avg Entry Fee Per Share */
            avg_entry_fee_per_share: number;
            /** Cumulative Quantity Bought */
            cumulative_quantity_bought: number;
            /** Cumulative Entry Fees */
            cumulative_entry_fees: number;
            /** Cumulative Exit Fees */
            cumulative_exit_fees: number;
            /** Realized Pnl */
            realized_pnl: number;
            /** Opened At */
            opened_at: string | null;
            /** Closed At */
            closed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * PositionStatus
         * @enum {string}
         */
        PositionStatus: "PLANNED" | "OPEN" | "PARTIALLY_CLOSED" | "CLOSED" | "CANCELLED";
        /** PriceBarOut */
        PriceBarOut: {
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Volume */
            volume: number;
            /** Previous Close */
            previous_close: number | null;
            /** Change */
            change: number | null;
            /** Change Percent */
            change_percent: number | null;
            /** Source */
            source: string;
            quality_status: components["schemas"]["DataQualityStatus"];
            /** Quality Notes */
            quality_notes: string[] | null;
        };
        /** ScanCandidateOut */
        ScanCandidateOut: {
            /** Symbol */
            symbol: string;
            /**
             * Scan Date
             * Format: date
             */
            scan_date: string;
            setup_type: components["schemas"]["SetupType"];
            /** Indicator Version */
            indicator_version: string;
            /** Score Version */
            score_version: string;
            /** Composite Score */
            composite_score: number;
            /** Trend Score */
            trend_score: number;
            /** Momentum Score */
            momentum_score: number;
            /** Volume Score */
            volume_score: number;
            /** Price Structure Score */
            price_structure_score: number;
            /** Volatility Score */
            volatility_score: number;
            /** Setup Quality Score */
            setup_quality_score: number;
            /** Risk Reward Score */
            risk_reward_score: number;
            /** Qualifying Conditions */
            qualifying_conditions: string[];
            /** Invalidation Conditions */
            invalidation_conditions: string[];
        };
        /** SectorPerformanceOut */
        SectorPerformanceOut: {
            /** Sector */
            sector: string;
            /** Instrument Count */
            instrument_count: number;
            /** Avg Return Pct */
            avg_return_pct: number;
        };
        /**
         * SetupType
         * @enum {string}
         */
        SetupType: "BREAKOUT" | "PULLBACK_CONTINUATION" | "MOMENTUM_CONTINUATION" | "MA_RECLAIM" | "VOLATILITY_SQUEEZE";
        /** StageStatusOut */
        StageStatusOut: {
            job_type: components["schemas"]["JobType"];
            last_status: components["schemas"]["JobStatus"] | null;
            /** Last Run Date */
            last_run_date: string | null;
            /** Last Finished At */
            last_finished_at: string | null;
            /** Is Stale */
            is_stale: boolean;
        };
        /** TradePlanCreate */
        TradePlanCreate: {
            /** Symbol */
            symbol: string;
            setup_type: components["schemas"]["SetupType"];
            /**
             * Plan Date
             * Format: date
             */
            plan_date: string;
            /** Capital */
            capital: number;
            /** Existing Positions */
            existing_positions?: components["schemas"]["PortfolioPositionIn"][];
        };
        /** TradePlanOut */
        TradePlanOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Instrument Id
             * Format: uuid
             */
            instrument_id: string;
            /** Scan Candidate Id */
            scan_candidate_id: string | null;
            setup_type: components["schemas"]["SetupType"];
            /**
             * Plan Date
             * Format: date
             */
            plan_date: string;
            /** Risk Version */
            risk_version: string;
            /** Score Version */
            score_version: string | null;
            /** Indicator Version */
            indicator_version: string | null;
            status: components["schemas"]["TradePlanStatus"];
            /** Rejection Reasons */
            rejection_reasons: string[];
            /** Entry Price */
            entry_price: number | null;
            /** Stop Price */
            stop_price: number | null;
            /** Target Prices */
            target_prices: number[];
            /** Quantity */
            quantity: number;
            /** Allocation Amount */
            allocation_amount: number;
            /** Allocation Pct */
            allocation_pct: number;
            /** Max Loss Amount */
            max_loss_amount: number;
            /** Risk Reward Ratio */
            risk_reward_ratio: number | null;
            /** Assumptions */
            assumptions: {
                [key: string]: unknown;
            };
            /** Invalidation Conditions */
            invalidation_conditions: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TradePlanStatus
         * @enum {string}
         */
        TradePlanStatus: "VALID" | "REJECTED";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    version_api_v1_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_instruments_api_v1_instruments_get: {
        parameters: {
            query?: {
                sector?: string | null;
                status?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_InstrumentOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_instrument_api_v1_instruments__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_instrument_prices_api_v1_instruments__symbol__prices_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                adjusted?: boolean;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PriceBarOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_instrument_corporate_actions_api_v1_instruments__symbol__corporate_actions_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CorporateActionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_instrument_indicators_api_v1_instruments__symbol__indicators_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                indicator_version?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_IndicatorSnapshotOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scan_candidates_api_v1_scanner_candidates_get: {
        parameters: {
            query?: {
                sector?: string | null;
                setup?: components["schemas"]["SetupType"] | null;
                min_score?: number | null;
                scan_date?: string | null;
                score_version?: string;
                sort?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ScanCandidateOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_instrument_candidates_api_v1_instruments__symbol__candidates_get: {
        parameters: {
            query?: {
                score_version?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ScanCandidateOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_backtest_runs_api_v1_backtests_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_BacktestRunOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_backtest_run_api_v1_backtests__backtest_run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backtest_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRunDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_backtest_trades_api_v1_backtests__backtest_run_id__trades_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                backtest_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_BacktestTradeOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_backtest_equity_curve_api_v1_backtests__backtest_run_id__equity_curve_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                backtest_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_EquityPointOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trade_plans_api_v1_risk_trade_plans_get: {
        parameters: {
            query?: {
                symbol?: string | null;
                setup_type?: components["schemas"]["SetupType"] | null;
                status?: components["schemas"]["TradePlanStatus"] | null;
                plan_date?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TradePlanOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_trade_plan_api_v1_risk_trade_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TradePlanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradePlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trade_plan_api_v1_risk_trade_plans__trade_plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trade_plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradePlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_executions_api_v1_executions_get: {
        parameters: {
            query?: {
                symbol?: string | null;
                position_id?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ExecutionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_execution_api_v1_executions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecutionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_positions_api_v1_positions_get: {
        parameters: {
            query?: {
                symbol?: string | null;
                status?: components["schemas"]["PositionStatus"] | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PositionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_planned_position_api_v1_positions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlannedPositionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_position_api_v1_positions__position_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_position_api_v1_positions__position_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_journal_api_v1_positions__position_id__journal_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_journal_api_v1_positions__position_id__journal_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JournalUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_performance_summary_api_v1_performance_summary_get: {
        parameters: {
            query?: {
                initial_capital?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformanceSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_performance_by_setup_api_v1_performance_by_setup_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupPerformanceOut"][];
                };
            };
        };
    };
    get_performance_by_sector_api_v1_performance_by_sector_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupPerformanceOut"][];
                };
            };
        };
    };
    get_performance_by_holding_period_api_v1_performance_by_holding_period_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupPerformanceOut"][];
                };
            };
        };
    };
    get_performance_by_score_bucket_api_v1_performance_by_score_bucket_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupPerformanceOut"][];
                };
            };
        };
    };
    get_performance_behavior_api_v1_performance_behavior_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BehaviorEntryOut"][];
                };
            };
        };
    };
    analyze_api_v1_ai_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisSnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_snapshots_api_v1_ai_snapshots_get: {
        parameters: {
            query?: {
                symbol?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AnalysisSnapshotOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_snapshot_api_v1_ai_snapshots__snapshot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisSnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_breadth_api_v1_intelligence_breadth_compute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BreadthComputeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BreadthSnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_breadth_api_v1_intelligence_breadth_get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BreadthSnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_breadth_history_api_v1_intelligence_breadth_history_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_BreadthSnapshotOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sector_performance_api_v1_intelligence_sector_performance_get: {
        parameters: {
            query: {
                as_of: string;
                lookback_days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectorPerformanceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_v1_intelligence_events_get: {
        parameters: {
            query?: {
                symbol?: string | null;
                as_of?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_EventOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_api_v1_alerts_get: {
        parameters: {
            query?: {
                alert_type?: components["schemas"]["AlertType"] | null;
                symbol?: string | null;
                trigger_date?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AlertOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_alerts_api_v1_alerts_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ops_status_api_v1_ops_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsStatusOut"];
                };
            };
        };
    };
    list_job_runs_api_v1_ops_job_runs_get: {
        parameters: {
            query?: {
                job_type?: components["schemas"]["JobType"] | null;
                status?: components["schemas"]["JobStatus"] | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_JobRunOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_calendar_days_api_v1_calendar_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CalendarDayOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
