from enum import StrEnum


class ListingStatus(StrEnum):
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    DELISTED = "DELISTED"


class DataQualityStatus(StrEnum):
    VALID = "VALID"
    INVALID = "INVALID"
    STALE = "STALE"
    SUSPECT = "SUSPECT"


class CorporateActionType(StrEnum):
    SPLIT = "SPLIT"
    REVERSE_SPLIT = "REVERSE_SPLIT"
    CASH_DIVIDEND = "CASH_DIVIDEND"
    STOCK_DIVIDEND = "STOCK_DIVIDEND"
    BONUS_ISSUE = "BONUS_ISSUE"
    RIGHTS_ISSUE = "RIGHTS_ISSUE"
    OTHER = "OTHER"


class IngestionStatus(StrEnum):
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    PARTIAL = "PARTIAL"


class SetupType(StrEnum):
    BREAKOUT = "BREAKOUT"
    PULLBACK_CONTINUATION = "PULLBACK_CONTINUATION"
    MOMENTUM_CONTINUATION = "MOMENTUM_CONTINUATION"
    MA_RECLAIM = "MA_RECLAIM"
    VOLATILITY_SQUEEZE = "VOLATILITY_SQUEEZE"


class ScanStatus(StrEnum):
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    PARTIAL = "PARTIAL"


class BacktestStatus(StrEnum):
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class ExecutionModel(StrEnum):
    NEXT_OPEN = "NEXT_OPEN"


class ExitReason(StrEnum):
    STOP = "STOP"
    TARGET = "TARGET"
    TIME = "TIME"
    END_OF_BACKTEST = "END_OF_BACKTEST"


class TradePlanStatus(StrEnum):
    VALID = "VALID"
    REJECTED = "REJECTED"


class ExecutionSide(StrEnum):
    BUY = "BUY"
    SELL = "SELL"


class PositionStatus(StrEnum):
    PLANNED = "PLANNED"
    OPEN = "OPEN"
    PARTIALLY_CLOSED = "PARTIALLY_CLOSED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class MarketRegime(StrEnum):
    RISK_ON = "RISK_ON"
    RISK_OFF = "RISK_OFF"
    NEUTRAL = "NEUTRAL"


class JobType(StrEnum):
    INGESTION = "INGESTION"
    INDICATORS = "INDICATORS"
    SCANNER = "SCANNER"
    RISK_PLANS = "RISK_PLANS"
    BREADTH = "BREADTH"
    ALERTS = "ALERTS"


class JobStatus(StrEnum):
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    PARTIAL = "PARTIAL"


class AlertType(StrEnum):
    SETUP_DETECTED = "SETUP_DETECTED"
    BREAKOUT = "BREAKOUT"
    PRICE_NEAR_ENTRY = "PRICE_NEAR_ENTRY"
    PRICE_NEAR_STOP = "PRICE_NEAR_STOP"
    PRICE_NEAR_TARGET = "PRICE_NEAR_TARGET"
    UNUSUAL_VOLUME = "UNUSUAL_VOLUME"
    STALE_DATA = "STALE_DATA"
    IMPORTANT_EVENT = "IMPORTANT_EVENT"
