from datetime import date, timedelta

from app.scanner.context import ScanPoint


def point(
    day_offset: int,
    close: float,
    *,
    start_date: date = date(2024, 1, 1),
    open_: float | None = None,
    high: float | None = None,
    low: float | None = None,
    volume: int = 1_000_000,
    sma_20: float | None = None,
    sma_50: float | None = None,
    sma_200: float | None = None,
    ema_20: float | None = None,
    ema_50: float | None = None,
    rsi_14: float | None = None,
    atr_14: float | None = None,
    macd: float | None = None,
    macd_signal: float | None = None,
    macd_histogram: float | None = None,
    bb_upper: float | None = None,
    bb_middle: float | None = None,
    bb_lower: float | None = None,
    volume_sma_20: float | None = None,
    relative_volume: float | None = None,
    rolling_high_20: float | None = None,
    rolling_low_20: float | None = None,
    return_1d: float | None = None,
    volatility_20: float | None = None,
) -> ScanPoint:
    return ScanPoint(
        trade_date=start_date + timedelta(days=day_offset),
        open=open_ if open_ is not None else close,
        high=high if high is not None else close,
        low=low if low is not None else close,
        close=close,
        volume=volume,
        sma_20=sma_20,
        sma_50=sma_50,
        sma_200=sma_200,
        ema_20=ema_20,
        ema_50=ema_50,
        rsi_14=rsi_14,
        atr_14=atr_14,
        macd=macd,
        macd_signal=macd_signal,
        macd_histogram=macd_histogram,
        bb_upper=bb_upper,
        bb_middle=bb_middle,
        bb_lower=bb_lower,
        volume_sma_20=volume_sma_20,
        relative_volume=relative_volume,
        rolling_high_20=rolling_high_20,
        rolling_low_20=rolling_low_20,
        return_1d=return_1d,
        volatility_20=volatility_20,
    )
